# Global parameters, no need to modify /!\
base_url_parameters:
  expanded: 1
  format: JSON
  filter_limit: -1
  module: API
  period: day

# Specify requests to be made in order to set the database properly
requests:
  visits:
    url_parameters:
      method: API.get
      format_metrics: 1
    need_transpose: True
    index_column_new_name: date
  pages:
    url_parameters:
      method: Actions.getPageUrls
      flat: 1
    date_range: True
  referrers:
    url_parameters:
      method: Referrers.getReferrerType
      format_metrics: 1
    date_range: True
  user_language:
    url_parameters:
      method: UserLanguage.getLanguage
      period: range
  downloads:
    url_parameters:
      method: Actions.getDownloads
      flat: 1
    date_range: True
  entry_pages:
    url_parameters:
      method: Actions.getEntryPageUrls
      flat: 1
    date_range: True
  exit_pages:
    url_parameters:
      method: Actions.getExitPageUrls
      flat: 1
    date_range: True
  users_country:
    url_parameters:
      method: UserCountry.getCountry
      format_metrics: 1
    date_range: True
  users_city:
    url_parameters:
      method: UserCountry.getCity
      format_metrics: 1
    date_range: True